@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas Francisco",
  "email": "lucas5@mail.com",
  "password": "123456"
}

###

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lucas@mail.com",
  "password": "123456"
}

###

# @name create_question

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 3",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions

GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug

GET {{baseUrl}}/questions/nova-pergunta-3
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question

PUT {{baseUrl}}/questions/dfe794a5-6a66-48f8-8219-88f9c3e2aab0
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "New title",
  "content": "New content"
}
