version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nest-clean
  cache:
    container_name: nest-clean-cache
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
